### PR TITLE
Merge master in to resolve merge conflicts

### PR DESCRIPTION
**Pull request by kevinrobinson**
This resolves merge conflicts in https://github.com/studentinsights/studentinsights/pull/1154 introduced by https://github.com/studentinsights/studentinsights/pull/1182.

### CODE REVIEW

**Comment by gabivoicu** [comment]
Thank you for creating this PR, @kevinrobinson! Should I do a `Rebase and merge`, a `Squash and merge` or a `Create merge commit`? From what I know so far, rebase sounds like the way to go but wanted to double check.

**Comment by kevinrobinson** [comment]
@gabivoicu You can just merge this pull request here with the big green button in the GitHub UI.  That will merge these commits into the `1087-student-contact-info` branch in your GitHub repo, and then on the command line you can `git pull` the `gabivoicu/studentinsights` repository down to your local machine to see the changes locally and keep working.

Let me know if you have any other questions or run into any issues!

**Comment by gabivoicu** [comment]
@kevinrobinson The big green button on here has a drop down that gives those three options (Rebase, Squash and Create merge commit) and I know different teams have different preferences, that's what I was asking about. But if it doesn't make a difference, I can merge w/ a Create merge commit. Let me know if that would be a problem at all.

**Comment by kevinrobinson** [comment]
@gabivoicu ah sorry I didn't realize!  Sounds like you all talked this out on the caller earlier but let me know if there's anything else I can help with.

**Pull request merged**
